// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0UuhfzM-O0F43kIA4X4KR_emeV8L9h48',
    appId: '1:475483167306:web:ed6b533086a82fd54624b3',
    messagingSenderId: '475483167306',
    projectId: 'habit-helper-fb988',
    authDomain: 'habit-helper-fb988.firebaseapp.com',
    storageBucket: 'habit-helper-fb988.appspot.com',
    measurementId: 'G-49G7NRQRDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfVsawD2vmY6zwlm-IpHTv_sFoxirsu_c',
    appId: '1:475483167306:android:fc702e92907564de4624b3',
    messagingSenderId: '475483167306',
    projectId: 'habit-helper-fb988',
    storageBucket: 'habit-helper-fb988.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY_fFA_y7gl3ZYupKrmnqtxihIGOLgSaw',
    appId: '1:475483167306:ios:db525b0303542c9a4624b3',
    messagingSenderId: '475483167306',
    projectId: 'habit-helper-fb988',
    storageBucket: 'habit-helper-fb988.appspot.com',
    iosBundleId: 'com.example.habitHammer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY_fFA_y7gl3ZYupKrmnqtxihIGOLgSaw',
    appId: '1:475483167306:ios:db525b0303542c9a4624b3',
    messagingSenderId: '475483167306',
    projectId: 'habit-helper-fb988',
    storageBucket: 'habit-helper-fb988.appspot.com',
    iosBundleId: 'com.example.habitHammer',
  );
}
